apiVersion: v1
kind: Service
metadata:
  name: organnize-api-service
spec:
  selector:
    app: organnize-api-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
